spring:
  cloud:
    config:
      uri: ${CONFIG_HOST:http://localhost:8888}
      name: ${CONFIG_NAME:api-gateway-local}
      profile: ${CONFIG_PROFILE:default}
  config:
    import: configserver:${CONFIG_HOST:http://localhost:8888}


